name: Frontend CI + Sonar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    name: Lint → Test+Coverage → Build → SonarQube
    runs-on: ubuntu-latest
    strategy:
      matrix: { node-version: [18.x] }

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarQube blame info

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm ci

<<<<<<< HEAD
      

=======
>>>>>>> 8e4ac7af0c5dbf05ec7cdb52c38a9996d3778ff9
      - name: Run unit tests with coverage
        run: npm test -- --coverage

      - name: Build production bundle
        run: npm run build

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
